#pragma once

#include <string>
#include <vector>
#include <cstdint>

namespace progressive {

// ---- Room Display Name Resolver ----
// Faithful port from original Kotlin:
//   org.matrix.android.sdk.internal.session.room.membership.RoomDisplayNameResolver.kt (184 lines)
//
// This implements the room name calculation algorithm from matrix-js-sdk:
//   https://github.com/matrix-org/matrix-js-sdk/blob/develop/lib/models/room.js#L617
//
// Algorithm (from original Kotlin:59-166):
//   1. If room has m.room.name state event → use that name
//   2. If room has m.room.canonical_alias → use the alias
//   3. For INVITE rooms → show inviter's name
//   4. For JOIN rooms → compute from members:
//      a. Use "heroes" list if available (up to 5)
//      b. Otherwise take other members (not self, not excluded)
//      c. Format: 0→empty, 1→"Alice", 2→"Alice and Bob",
//         3→"Alice, Bob and Carol", 4→"Alice, Bob, Carol and Dave",
//         5+→"Alice, Bob, Carol and N others"

enum class RoomMembership {
    Unknown,
    Join,
    Invite,
    Leave,
    Ban,
    Knock
};

struct RoomMember {
    std::string userId;
    std::string displayName;
    std::string avatarUrl;
    RoomMembership membership = RoomMembership::Unknown;
    bool isUnique = true;  // displayName is unique among members
};

struct RoomName {
    std::string name;          // display name
    std::string normalizedName; // normalized for sorting (lowercase, stripped)
};

// ==== RoomNameInfo ====
//
// Original Kotlin (RoomDisplayNameResolver.kt combined result):
//   Complete room name resolution result with source tracking.
//   Tracks where the name came from for UI decisions
struct RoomNameInfo {
    std::string name;                  // final computed display name
    std::string computedDisplayName;   // same as name, used in Kotlin compat layer
    bool isNameFromState = false;      // name came from m.room.name state event
    bool isNameFromAlias = false;      // name came from canonical alias
    bool isNameFromMembers = false;    // name was computed from member list
    bool isNameFromHeroes = false;     // name used heroes subset
    bool isNameFromInviter = false;    // name is the inviter's display name
    int memberCount = 0;              // number of members used to compute the name
    int totalMemberCount = 0;         // total members in the room
    std::vector<std::string> sourceMemberNames; // member names used in computation

    // Original Kotlin: convenience check if name was auto-generated
    bool isAutoGenerated() const {
        return isNameFromMembers || isNameFromHeroes;
    }

    // Original Kotlin: check if this is an "empty room" result
    bool isEmptyRoom() const {
        return memberCount == 0 && !isNameFromState && !isNameFromAlias;
    }
};

// ==== Room Name Error ====
// Original Kotlin: validation errors for room name changes

enum class RoomNameError {
    NONE,
    TOO_LONG,       // Exceeds max length
    TOO_SHORT,      // Below min length
    INVALID_CHARS,  // Contains disallowed characters
    EMPTY,          // Name is empty or whitespace only
    DUPLICATE       // Same as current room name
};

// Describe a room name error as human-readable text.
// Original Kotlin: getRoomNameError() for UI display
std::string getRoomNameError(RoomNameError error);

// ==== Room Name Config ====
// Original Kotlin: configuration for room name validation

struct RoomNameConfig {
    int maxLength = 255;             // Matrix spec: max room name length
    int minLength = 1;               // Min length (1 char required)
    std::string allowedRegex;        // Regex for allowed chars (empty = no restriction)
    std::string disallowedRegex;     // Regex for disallowed chars (empty = no restriction)
};

// Get default room name config per Matrix spec.
// Original Kotlin: standard Matrix room name limits
RoomNameConfig getDefaultRoomNameConfig();

// ==== Room Name Event Validator ====
// Original Kotlin: validate room name change events

struct RoomNameEventValidator {
    // Validate a proposed room name against config.
    // Returns NONE if valid, or the specific error code.
    static RoomNameError validateRoomName(
        const std::string& name,
        const RoomNameConfig& config = getDefaultRoomNameConfig(),
        const std::string& currentName = "");

    // Sanitize a room name by stripping invalid characters.
    // Removes leading/trailing whitespace and disallowed chars.
    static std::string sanitizeRoomName(
        const std::string& name,
        const RoomNameConfig& config = getDefaultRoomNameConfig());
};

// ==== Room Name History ====
// Original Kotlin: track room name changes over time

struct RoomNameHistoryEntry {
    std::string name;        // The room name at that point in time
    int64_t timestampMs = 0; // When the name was set
};

struct RoomNameHistory {
    std::string roomId;
    std::vector<RoomNameHistoryEntry> entries;  // Ordered oldest → newest

    // Get the current (most recent) name.
    std::string currentName() const;

    // Get the previous name before current.
    std::string previousName() const;

    // Check if the room has ever been renamed.
    bool wasRenamed() const;
};

// Track a room name change — record in history.
// Original Kotlin: append to room name history
void trackRoomNameChange(
    RoomNameHistory& history,
    const std::string& roomId,
    const std::string& newName,
    int64_t timestampMs);

// Format room name history as human-readable.
// "Renamed from 'Old Name' to 'New Name'"
// "Renamed 3 times, currently 'Newest Name'"
std::string formatRoomNameHistory(const RoomNameHistory& history);

// Compute the room display name using the matrix-js-sdk algorithm.
// Original Kotlin (RoomDisplayNameResolver.kt:resolve):
//   fun resolve(realm: Realm, roomId: String): RoomName
RoomName computeRoomDisplayName(
    const std::string& roomNameState,      // m.room.name content (empty if not set)
    const std::string& canonicalAlias,     // m.room.canonical_alias content
    const std::vector<RoomMember>& heroes, // hero users (empty if not set)
    const std::vector<RoomMember>& activeMembers, // active (joined + invited) members
    const std::vector<RoomMember>& leftMembers,   // left members
    const std::string& myUserId,           // current user ID
    const std::string& directUserId,       // DM partner (empty if not DM)
    const std::string& inviterName,        // inviter's display name (for invite rooms)
    int invitedCount,                      // number of invited members
    int joinedCount,                       // number of joined members
    bool isInvite,                         // this user is invited
    const std::vector<std::string>& excludedUserIds = {} // users to exclude
);

// Normalize a display name for sorting.
// Original Kotlin: Normalizer.normalize(this)
std::string normalizeRoomName(const std::string& name);

// Check if a display name is unique among members.
bool isUniqueDisplayName(const std::vector<RoomMember>& members, const std::string& displayName);

// Resolve member name with disambiguation.
// Original Kotlin: resolveRoomMemberName(member, helper)
//   val isUnique = helper.isUniqueDisplayName(member.displayName)
//   if (isUnique) displayName else "displayName (userId)"
std::string resolveMemberName(
    const RoomMember& member,
    const std::vector<RoomMember>& allMembers);

// Get a fallback name for an empty room.
// "Empty Room" for group rooms, user ID for DMs
std::string getEmptyRoomName(bool isDirect, const std::vector<std::string>& leftMemberNames);

// Format room name as JSON.
std::string roomNameToJson(const RoomName& name);

// Parse a room name state event content JSON.
// {"name": "My Room Name"}
std::string parseRoomNameContent(const std::string& contentJson);

// Parse a canonical alias state event content JSON.  
// {"alias": "#myroom:server.org"}
std::string parseCanonicalAliasContent(const std::string& contentJson);

// ==== New Room Name Utilities ====

// Original Kotlin: Format a list of member names into a comma-separated string
//   Uses English oxford comma style: "Alice, Bob, and Carol"
//   For 4+: "Alice, Bob, Carol, and Dave"
//   For 5+: "Alice, Bob, Carol, and 2 others"
std::string formatMemberNameList(const std::vector<std::string>& memberNames);

// Original Kotlin: Full room name resolution combining all name sources
//   Returns RoomNameInfo with source tracking metadata
//   Wraps computeRoomDisplayName() and adds source attribution
RoomNameInfo resolveRoomName(
    const std::string& roomNameState,
    const std::string& canonicalAlias,
    const std::vector<RoomMember>& heroes,
    const std::vector<RoomMember>& activeMembers,
    const std::vector<RoomMember>& leftMembers,
    const std::string& myUserId,
    const std::string& directUserId,
    const std::string& inviterName,
    int invitedCount,
    int joinedCount,
    bool isInvite,
    const std::vector<std::string>& excludedUserIds = {}
);

// Original Kotlin: Determine if a room name was auto-generated vs. set explicitly
//   Auto-generated: name comes from members list or heroes
//   Explicit: name comes from m.room.name or canonical_alias state events
bool isRoomNameGenerated(const RoomNameInfo& info);

// Original Kotlin: Build a RoomNameInfo JSON representation for JNI bridge
std::string roomNameInfoToJson(const RoomNameInfo& info);

} // namespace progressive
